name: CI
on: [ push, pull_request ]
jobs:
  build:

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 20 ]
        integration-deps:
        - "" # as defined in package.json

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install dependencies for integration test
      if: ${{ matrix.integration-deps != '' }}
      run: npm install ${{ matrix.integration-deps }}
    - name: Project setup
      uses: bpmn-io/actions/setup@latest
    - name: Build
      if: ${{ matrix.integration-deps != '' }}
      run: npm run all
    - name: Build with coverage
      if: ${{ matrix.integration-deps == '' }}
      env:
        COVERAGE: 1
      run: npm run all
    - name: Upload coverage
      if: ${{ matrix.integration-deps == '' }}
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
